[Task-3] - Undo add and remove from reading list
milanmishra/web-ui-developer-puzzle pull request #4
Opened 2021-08-08 13:17 UTC by milanmishra

### TASK 3 - UNDO ADD AND REMOVE FROM READING LIST

          * Task 3 is to add Undo functionality on the addition and removal of the book to and from the reading list 
             respectively. An appropriate message will be displayed in the Snackbar with Undo as an action.
          * When a user is adding any book to the reading list, a snackbar will be displayed which tells the user about 
             which book is getting added and an UNDO action. When we click on the UNDO button, the added book 
             will be removed from the reading list. 
          * When a user is removing any book from the reading list, a snackbar will be displayed which tells the user
             about which book is getting removed from the reading list and an UNDO action. When we click on the
             UNDO button, the removed book will be added again to the reading list.

### CODE CHANGES

         * Added the snackbar for the UNDO functionality for both addition and removal of the book in addBook$ 
            and removeBook$ effects. 
            File: reading-list-effects.ts.
         * Updated all the required unit test cases and e2e test cases for both components and states.
         * Also added styling for the snackbar.
         * The snackbar will be displayed for 3 seconds.

### Unit test case Report

![UnitTestCase_Report](https://user-images.githubusercontent.com/85860307/128633265-6fcc2ab4-b6e3-417c-9d20-aab3d7abd7f2.PNG)

### Lint Report

![Lint_Report](https://user-images.githubusercontent.com/85860307/128633272-3b1b9e5b-1620-4b18-92b1-9f1bd3cc9709.PNG)

### E2E Report

![E2E-Report](https://user-images.githubusercontent.com/85860307/128633277-6844bd81-5606-425b-949f-51603f73ba57.PNG)

###  Working app

1. When a user adds a book to the reading list, snackbar will be displayed at the bottom with a description
    about which book is being added to the list, and the UNDO action. 
    The Undo action will undo the addition of the book to the reading list.

![image](https://user-images.githubusercontent.com/85860307/128509171-65260c59-fde5-4735-9360-7550135da713.png)

2. Similarly when a user removes a book from the reading list, Snackbar will be displayed with a description about
    which book is being removed, and the UNDO action.
    The Undo action will undo the removal of the book from the reading list.

![image](https://user-images.githubusercontent.com/85860307/128509205-15032e0e-6007-4c40-8c82-9eddf0a51f21.png)

2021-08-10 07:32 UTC, milanmishra commented on libs/books/data-access/src/lib/+state/reading-list.actions.ts
> +  props<{ book: Book, showSnackBar: boolean }>()
Updating addToReadingList action with one more value i.e showSnackBar. 
```
  props<{ book: Book, showSnackBar: boolean }>()
```

2021-08-10 07:34 UTC, milanmishra commented on libs/books/data-access/src/lib/+state/reading-list.effects.ts
> +              this.openSnackbar(book, null);
When showSnackbar is true then openSnackbar() function will be called which will display the snackBar with appropirate message and action.
```
              this.openSnackbar(book, null);
```

2021-08-10 07:35 UTC, milanmishra commented on libs/books/data-access/src/lib/+state/reading-list.effects.ts
> +  private openSnackbar(book: Book, item: ReadingListItem) {
This function will display the snackBar and perform undo actions accordingly.
```
  private openSnackbar(book: Book, item: ReadingListItem) {
```

2021-08-10 07:37 UTC, milanmishra commented on libs/shared/styles/src/lib/base.scss
> +
Added below styling for snackBar container and Undo button.

2021-08-11 15:53 UTC, ASreedh1 requested changes

2021-08-11 15:53 UTC, ASreedh1 commented on apps/okreads-e2e/src/integration/reading-list.spec.ts
> +    cy.get('input[type="search"]').type('test3');
you must first remove all the reading list items and then start the test

2021-08-11 15:53 UTC, ASreedh1 commented on libs/books/data-access/src/lib/+state/reading-list.effects.ts
> +    snackBarRef.onAction().subscribe(() =>
this is not the right approach to write the effects. DO NOT subscribe inside effects and DO NOT call this.store.dispatch in effects.

2021-08-11 15:53 UTC, ASreedh1 commented on libs/books/data-access/src/lib/+state/reading-list.effects.ts
> +    const snackBarRef = this.snackBar.open(
why do you need to assign snackBar to a constant?

2021-08-11 15:53 UTC, ASreedh1 commented on libs/books/data-access/src/lib/+state/reading-list.effects.spec.ts
> +    it('should undo remove book from the reading list when snackbar action is clicked', () => {
use done in test case to test async operations

2021-08-11 15:53 UTC, ASreedh1 commented on libs/books/data-access/src/lib/+state/reading-list.effects.spec.ts
> +    it('should not open snackbar when snackbar undo remove from list action is performed once', () => {
use done

2021-08-11 15:53 UTC, ASreedh1 commented on libs/books/data-access/src/lib/+state/reading-list.effects.spec.ts
> +    it('should not open snackbar when snackbar undo add to list action is performed once', () => {
use done in test cases to test async operations

2021-08-11 15:53 UTC, ASreedh1 commented on libs/books/data-access/src/lib/+state/reading-list.effects.spec.ts
> +    it('should undo add book to the reading list when snackbar action is clicked', () => {
use done

2021-08-11 15:53 UTC, ASreedh1 commented on libs/books/data-access/src/lib/+state/reading-list.effects.spec.ts
> +      actions.next(
use Observable instead of ReplaySubject

2021-08-11 15:53 UTC, ASreedh1 commented on apps/okreads-e2e/src/integration/reading-list.spec.ts
> +    cy.get('input[type="search"]').type('test2');
see above comment

2021-08-21 12:32 UTC, milanmishra commented on libs/books/data-access/src/lib/+state/reading-list.effects.ts
> +    snackBarRef.onAction().subscribe(() =>
This review comment has been resolved. Please have a look.

2021-08-21 12:32 UTC, milanmishra commented on libs/books/data-access/src/lib/+state/reading-list.effects.ts
> +    const snackBarRef = this.snackBar.open(
This review comment has been resolved. Please have a look.

2021-08-21 12:33 UTC, milanmishra commented on libs/books/data-access/src/lib/+state/reading-list.effects.spec.ts
> +    it('should undo remove book from the reading list when snackbar action is clicked', () => {
This review comment has been resolved. Please have a look.

2021-08-21 12:33 UTC, milanmishra commented on libs/books/data-access/src/lib/+state/reading-list.effects.spec.ts
> +    it('should not open snackbar when snackbar undo remove from list action is performed once', () => {
This review comment has been resolved. Please have a look.

2021-08-21 12:33 UTC, milanmishra commented on libs/books/data-access/src/lib/+state/reading-list.effects.spec.ts
> +    it('should not open snackbar when snackbar undo add to list action is performed once', () => {
This review comment has been resolved. Please have a look.

2021-08-21 12:33 UTC, milanmishra commented on libs/books/data-access/src/lib/+state/reading-list.effects.spec.ts
> +    it('should undo add book to the reading list when snackbar action is clicked', () => {
This review comment has been resolved. Please have a look.

2021-08-21 12:33 UTC, milanmishra commented on libs/books/data-access/src/lib/+state/reading-list.effects.spec.ts
> +      actions.next(
This review comment has been resolved. Please have a look.

2021-08-23 14:50 UTC, closed without merging

2021-08-24 07:10 UTC, milanmishra commented on apps/okreads-e2e/src/integration/reading-list.spec.ts
> +    cy.get('input[type="search"]').type('test3');
This review comment has been resolved. Please have a look.